version: '3'
services:
  tp2:
    image: 859f710e3da6
    environment:
      - ENVIRONMENT=dev
    volumes:
      - logs
  tp2front:
    image: a0325ad54c85
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=back
    links:
      - "tp2:back"
    #volumes:
     # - logs

