version: '3'
services:
  tp2:
    image: 859f710e3da6
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=dev
  tp2front:
    image: a0325ad54c85
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=172.17.0.1
